### PR TITLE
Switch from UDP to TCP (permit routing through SOCKS)

### PR DESCRIPTION
**Pull request by jpritikin**
With this change, I managed to route DNS through SOCKS (ssh tunnel) in concert with tsocks.

### CODE REVIEW

**Comment by hadess** [comment]
This needs to be an option, similarly to how we select nameservers. Forcefully setting resolution option might fix your use case, but would like break others...

**Comment by jpritikin** [comment]
On Sun, Feb 19, 2017 at 03:09:03PM -0800, hadess wrote:
>    This needs to be an option, similarly to how we select nameservers.
>    Forcefully setting resolution option might fix your use case, but would
>    like break others...

OK, like an environment variable?

**Comment by hadess** [comment]
Yes, I think a check for `getenv("FORCE_TCP") != NULL` would set that option. Also add a comment that this forces using TCP.

**Comment by jpritikin** [comment]
Better just make the name of the environment variable self explanatory.

**Pull request closed without merging**
